# -*- coding: utf-8 -*-
"""MVP2 405202600083 Joao Guilherme C Loureiro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0mG9iTA1w7ie7nnRTLaLyLEHAc3ZJC4

# **MVP Machine Learning & Analytics**

**Nome:** Joao Guilherme Cartaxo Loureiro

**Matrícula:** 4052026000083

**Data:** _05/07/2026_

**Tipo de problema:** _Séries Temporais_

**Dataset:** ["Will EVs Replace Petrol Cars?"](https://www.kaggle.com/datasets/aryanmdev/will-evs-replace-petrol-cars)

# **1. Definição do problema**

## 1.1 Descrição do problema

**Contexto**

O mercado automotivo global está passando por uma transição para veículos elétricos, impulsionada por preocupações ambientais, avanços tecnológicos e políticas públicas. No Brasil, essa transição enfrenta desafios específicos, como o alto custo inicial dos veículos elétricos, infraestrutura limitada de recarga e particularidades da matriz energética.

Nesse contexto, entender se veículos elétricos dominarão o mercado brasileiro. A viabilidade econômica dos veículos elétricos em comparação aos veículos a combustão é essencial para consumidores, montadoras e formuladores de políticas públicas.

**Perguntas**

Em quais condições a venda de veículos elétricos se torna sustentável no Brasil? Em outras palavras, em que condições veículos elétricos presentam vantagem econômica em relação aos veículos a combustão no Brasil, considerando custo total de propriedade, custo operacional e perfil de uso do consumidor? Quando a venda de elétricos superaria a de veículos a combustão?

## 1.2 Objetivo do MVP

Prever, utilizando séries temporais, o share de veículos elétricos no Brasil.

## 1.3 Tipo de problema

É um problema de séries temporais.
As variáveis que determinam a viabilidade são dinâmicas e interdependentes, ou seja, mudam mês a mês e se influenciam mutuamente.

## 1.4 Premissas, hipóteses e critérios de sucesso

**Hipóteses iniciais:**

1. **A adoção de veículos elétricos está mais associada a fatores regulatórios e econômicos do que a subsídios diretos.**\
Espera-se que variáveis como *emission_regulation_score* e fuel_price_usd_per_liter* apresentem correlação com *ev_market_share* pelo menos duas vezes maior que *ev_subsidy_usd*, indicando que políticas de precificação e regulação têm mais influência sobre a adoção do que incentivos financeiros isolados.

2. **Variáveis estruturais de mercado têm poder preditivo suficiente para estimar o share de veículos elétricos com erro médio inferior a 5 pontos percentuais.**\
Espera-se que um modelo treinado com features como preço de combustível,
regulação ambiental, PIB per capita e histórico de adoção supere
amplamente uma predição ingênua por inércia temporal, reduzindo o RMSE em
pelo menos 50% em relação ao baseline.

3. **O Brasil está em estágio inicial da curva de difusão de veículos elétricos, com trajetória de crescimento acelerado a partir de 2021.**\
Espera-se que a série histórica brasileira apresente o formato característico de uma curva S, com crescimento quase nulo por uma década, seguido de inflexão visível e aceleração progressiva, e que o share do Brasil em 2025 esteja significativamente abaixo da mediana global, confirmando que a transição ainda está em estágio emergente.

# **2. Ambiente, bibliotecas e reprodutibilidade**

Reunião das importações, configuração de seed e informações básicas do ambiente.
"""

#Importacao de pacotes
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import time
from sklearn.preprocessing import StandardScaler
from matplotlib import cm
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit
from scipy.stats import randint, uniform
from xgboost import XGBRegressor

"""# **3. Seleção e carga dos dados**

## 3.1 Fonte dos dados

## Seleção de Dados

**Dataset:** ["Will EVs Replace Petrol Cars?"](https://www.kaggle.com/datasets/aryanmdev/will-evs-replace-petrol-cars)

O dataset a ser analisado é público e apresenta dados globais sobre vendas de veículos elétricos e a combustão, infraestrutura de recarga, preços de energia, indicadores econômicos e políticas públicas ao longo do tempo. Ele permite investigar os principais fatores que influenciam a adoção de veículos elétricos, como custo relativo de energia, disponibilidade de infraestrutura e incentivos governamentais.

Embora não contenha dados específicos do Brasil nem o custo inicial dos veículos, o dataset possibilita a construção de análises comparativas entre países e a simulação de cenários, permitindo inferir em quais condições os veículos elétricos se tornam economicamente sustentáveis. Dessa forma, ele é adequado para testar hipóteses relacionadas a custo operacional, crescimento de mercado, impacto de políticas públicas e infraestrutura na adoção de veículos elétricos.

Não há questões de de ética, privacidade, confidencialidade ou licença associadas ao dataset.

## 3.1 Carga dos dados
"""

#Importacao do dataset
url = "https://raw.githubusercontent.com/jogcl/Analise-EV/refs/heads/main/ev_vs_petrol_dataset_v3.csv"

#Leitura do dataset e carga em dataframe
dataset = pd.read_csv(url)

#Teste de correta leitura
dataset.head()

"""## 3.2 Visão geral do dataset

### **Atributos do dataset**

>**Identificação e contexto**\
*country*: País ao qual os dados se referem\
*region*: Região geográfica do país (ex: Europa, Ásia, América)\
*year*: Ano da observação

>**Segmentação de veículos**\
*vehicle_segment*: Categoria do veículo (ex: compacto, SUV, médio)\
*powertrain_type*: Tipo de motorização (elétrico, gasolina, diesel, etc.)

>**Mercado automotivo**\
*ev_sales*: Número de veículos elétricos vendidos\
*petrol_car_sales*: Número de veículos a gasolina vendidos\
*diesel_car_sales*: Número de veículos a diesel vendidos\
*total_vehicle_sales*: Total de veículos vendidos (todas as categorias)\
*ev_market_share*: Participação dos veículos elétricos no total de vendas (%)

>**Infraestrutura de recarga**\
*charging_stations*: Número total de estações de recarga disponíveis\
*fast_chargers_share*: Proporção de carregadores rápidos (%)

>**Tecnologia dos veículos**\
*avg_ev_range_km*: Autonomia média dos veículos elétricos (em quilômetros)

>**Variáveis econômicas**\
*fuel_price_usd_per_liter*: Preço do combustível (gasolina/diesel) por litro em USD\
*electricity_price_usd_per_kwh*: Preço da eletricidade por kWh em USD
*gdp_per_capita*: PIB per capita do país

>**Demografia**\
*urban_population_percent*: Percentual da população que vive em áreas urbanas

>**Sustentabilidade e políticas públicas**\
*co2_emissions_transport_mt*: Emissões de CO₂ do setor de transporte (em milhões de toneladas)\
*emission_regulation_score*: Índice que representa o nível de rigor das *   regulações ambientais\
*ev_subsidy_usd*: Valor de subsídios governamentais para veículos elétricos (em USD)

>**Crescimento e adoção**\
*ev_growth_rate_yoy*: Taxa de crescimento anual das vendas de veículos elétricos (%)\
*is_ev_dominant*: Indicador binário (0 ou 1) que mostra se veículos elétricos já são predominantes no mercado

### **Dimensões do dataset**
"""

#mostrar dimensoes do dataset
dataset.shape

"""Exibir Informações do Dataset"""

#mostrar informacoes do dataset
dataset.info()

"""Exibir os 10 Primeiros Registros do Dataset"""

# Exibir as primeiras 10 linhas do Dataset para verificar o carregamento
dataset.head(10)

"""Exibir os 10 Ultimos Registros do Dataset"""

# Exibir as ultimas 10 linhas do Dataset para verificar o carregamento
dataset.tail(10)

"""**Sanidade**

Aparentemente, com base nas dez primeiras e dez últimas linhas do dataset, os dados estão corretos.

### **Qualidade do dataset**
"""

#Avaliar "missings" por atributo
missing = dataset.isnull().sum().sort_values(ascending=False)
missing_pct = (dataset.isnull().mean() * 100).sort_values(ascending=False)

qualidade_missing = pd.DataFrame({
    "faltantes": missing,
    "percentual_%": missing_pct
})

print(qualidade_missing)

#Avaliar se existem linhas duplicadas

#Ver se existem registros repetidos
print("Duplicadas:", dataset.duplicated().sum())

#Se existem registro repetidos, ver quais são
dataset[dataset.duplicated()]

"""## 3.3 Dicionário de dados

| Categoria | Atributo | Tipo | Será usada no modelo? | Observações |
|---|---|---|---|---|
| Identificação e contexto | Country | Object | Não | Identificador de grupo, não preditor |
| Identificação e contexto | Region | Object | Não | Identificador de grupo derivado de 'Country', não preditor |
| Identificação e contexto | Year | Int | Sim | Feature temporal |
| Segmentação de veículos | Vehicle Segment | Object | Sim | Feature categórica |
| Segmentação de veículos | Powertrain Type | Object | Não | Sem variância útil |
| Mercado automotivo | EV Sales | Int | Não | Relação direta com o target |
| Mercado automotivo | Petrol Car Sales | Int | Não | Redundante com 'Total Vehicle Sales' - Total Vehicle Sales ≈ EV Sales + Petrol Car Sales + Diesel Car Sales |
| Mercado automotivo | Diesel Car Sales | Int | Não | Redundante com 'Total Vehicle Sales' - Total Vehicle Sales ≈ EV Sales + Petrol Car Sales + Diesel Car Sales |
| Mercado automotivo | Total Vehicle Sales | Int | Sim | Feature de mercado |
| **Mercado automotivo** | **EV Market Share** | **Float** | **Sim** | **Target** |
| Infraestrutura de recarga | Charging Stations | Int | Sim | Feature de infraestrutura |
| Infraestrutura de recarga | Fast Chargers Share | Float | Sim | Feature de infraestrutura |
| Tecnologia dos veículos | Avg EV Range (km) | Int | Não | Incluí-la introduz multicolinearidade com 'Year' e não acrescenta poder preditivo específico ao Brasil  |
| Variáveis econômicas | Fuel Price (USD/l) | Float | Sim | Feature econômica |
| Variáveis econômicas | Electricity Price (USD/kwh) | Float | Sim | Feature econômica |
| Variáveis econômicas | GDP Per Capita | Int | Sim | Feature econômica |
| Demografia | Urban Population (%) | Float | Sim | Feature demográfica |
| Sustentabilidade e políticas públicas | CO2 Emissions Transport (Millions of Tons) | Float | Não |  Consequência, não causa |
| Sustentabilidade e políticas públicas | Emissions Regulation Score | Float | Sim | Feature de regulação |
| Sustentabilidade e políticas públicas | EV Subsidy (USD) | Int | Sim | Feature econômica |
| Crescimento e adoção | EV Growth Rate YoY (%) | Float | Não | Relação indireta com o target |
| Crescimento e adoção | EV is Dominant | Int | Não | Target derivado de 'EV Market Share' e binário grosseiro |

## 3.4 Observações gerais
   1. Converter categóricas para category. Não está incorreto, mas melhora performance no futuro e deixa mais “semanticamente correto”\
*country* , *region*, *vehicle_segment* e *powertrain_type*

   2. Converter para variável binária\
   *is_ev_dominant*

   3. Validar se inteiros deveriam ser float\
Não é erro, apenads refinamento. Algumas colunas podem ser float dependendo da precisão desejada:\
*gdp_per_capita* e *ev_subsidy_usd* poderiam ser float (mas não obrigatório), pois poderiam ter casas decimais.

   4. Ponto de atenção\
Consistência lógica de *total_vehicle_sales* = soma dos outros

   5. Sumário\
A análise dos tipos de dados indicou que o dataset apresenta boa consistência estrutural, com variáveis categóricas corretamente representadas como texto e variáveis numéricas adequadamente tipadas como inteiros ou valores float. Não foram identificadas inconsistências relevantes nos tipos de dados. Como refinamento, variáveis categóricas podem ser convertidas para o tipo “category” e a variável binária pode ser convertida para o tipo "boolean", visando melhor eficiência e interpretação.

# **4. Análise exploratória dos dados**

## **4.1 Estatísticas descritivas**
"""

#Fazer resumo estatistico do dataset

# Configura o pandas para exibir números float com 2 casas decimais e sem notação científica
pd.set_option('display.float_format', lambda x: '%.2f' % x)

dataset.describe(include="all")

"""**Findings**
   1. Crescimento de EV muito alto (*ev_growth_rate_yoy*)\
mínimo: -40.96\
máximo: 300%\
média: 64%\
desvio padrão: 71
*   **Problema:** 300% é extremamente alto (triplica em 1 ano) -
alta variabilidade
*   **Insights:** mercado ainda imaturo (normal em EV) ou possíveis outliers fortes
*   **Ação:** tratar outliers ou analisar separadamentefortes

   2. Distribuição extremamente assimétrica/discrepante em vendas (*ev_sales*, *petrol_car_sales* e *total_vehicle_sales*)\
Exemplo: *ev_sales*\
mediana: ~2.7k\
máximo: 7.6 milhões
*   **Problema**: alta discrepância
*   **Insights:** poucos países dominam (China, EUA, etc.), cauda longa (heavy tail)
*   **Ação:** média não representa bem os dados e a análise pode ficar enviesada. Utilização de mediana e log-transform

   3. Market share de EV muito baixo em sua maioria (*ev_market_share*)\
mediana: 0.83%\
média: 6.3%\
máximo: 95%
alta discrepância
*   **Insights:** maioria dos países ainda está no início da adoção de veículos elétricos e poucos países puxam a média pra cima
*   **Ação:** média pode não representar bem os dados

   4. Dominância de veículos elétricos com muitos zeros (*is_ev_dominant*)\
valor quase sempre 0 ou Falso\
média: 0.018\
~1.8% dos casos são 1
*   **Problema**: dataset extremamente desbalanceado, o que é ruim para classificação e pode enviesar modelo
*   **Insights:** veículos elétricos não dominam o mercado

   5. Subsídios com muitos zeros (*ev_subsidy_usd*)\
25% = 0 ou Falso\
mediana ≈ 2794
*   **Insights:** praticamente nenhum país subsidia veículos elétricos
*   **Ação:** distribuição bimodal (zero vs positivo), o que pode pode exigir transformação

   6. Emissões com grande variação (*co2_emissions_transport_mt*)\
mínimo: 5.4\
máximo: 1900
*   **Problema**: diferença enorme
*   **Insights:** países pequenos vs gigantes
*   **Ação:** precisa normalizar

   7. PIB per capita muito disperso (*gdp_per_capita*)\
mínimo: 1.359\
máximo: 103.437
*   **Problema**: diferença enorme
*   **Insights:** forte desigualdade entre países pode dominar modelos
*   **Ação:** importante normalizar ou usar log

   8. Infraestrutura com grande variação (*charging_stations*)\
mínimo: 0\
máximo: 4.338.106
*   **Insights:** países desenvolvidos vs emergentes
*   **Ação:** importante normalizar por população (se tivesse) ou usar log

   9. Combinação desproporcional (*powertrain_type*)\
ICE (Internal Combustion Engine) com freq 1164 de 1200
*   **Problema**: diferença muito grande pode enviesar análises comparativas
*   **Insights:** dataset muito desbalanceado por tipo de motor

   10. Dataset é altamente heterogêneo
*   **Insights:** mistura países desenvolvidos/ricos com emergentes/pobres e mercados maduros com emergentes
*   **Problema**: gera outliers naturais e alta variância

Resumo: A análise evidenciou alta variabilidade nas variáveis do dataset, com presença de distribuições assimétricas e possíveis outliers, especialmente nas variáveis de vendas, crescimento de veículos elétricos e emissões. Observou-se também desbalanceamento em variáveis categóricas e binárias, como o predomínio de veículos a combustão e baixa incidência de mercados dominados por veículos elétricos. Além disso, a heterogeneidade entre países, refletida em variáveis como PIB per capita e infraestrutura, indica a necessidade de cautela na interpretação dos resultados, podendo exigir normalizações ou segmentações adicionais.

## **4.2 Histogramas**
"""

#Histogramas de atributos
dataset.hist(layout=(6,4), figsize=(25,20))
plt.show()

"""**Findings**

Os histogramas confirmam a presença de forte assimetria em diversas variáveis, especialmente aquelas relacionadas a vendas, infraestrutura e emissões, indicando concentração de valores em poucos países. Além disso, evidenciam que a adoção de veículos elétricos ainda é incipiente na maioria dos mercados, com distribuição de market share concentrada próxima de zero. Variáveis como preços de energia e regulação apresentam distribuição mais equilibrada, sendo mais adequadas para análises comparativas diretas. Esses padrões reforçam a necessidade de transformações no dataset

## **4.3 Densit plots**
"""

#Density Plot
dataset.plot(kind='density', subplots=True, layout=(6,4), sharex=False, figsize=(25,20))
plt.show()

"""**Findings**

Os density plots confirmam e refinam os achados dos histogramas, evidenciando forte assimetria em variáveis relacionadas a vendas, infraestrutura e emissões, com concentração de valores em poucos países. Além disso, revelam a presença de distribuições multimodais em variáveis como PIB per capita, preço da eletricidade e autonomia dos veículos elétricos, indicando a existência de diferentes grupos estruturais no dataset. Esses padrões reforçam a heterogeneidade entre países e a necessidade de transformações e segmentações para análises mais robustas

## **4.4 Box plots**
"""

#Boxplot do dataset
dataset.plot(kind='box', subplots=True, layout=(6,4), sharex=False, sharey=False, figsize=(25,20))
plt.show()

"""**Findings**

A análise conjunta de histogramas, density plots e boxplots evidencia forte assimetria e presença de outliers em diversas variáveis, especialmente nas relacionadas a vendas, infraestrutura e emissões. Esses padrões indicam concentração de valores em poucos países e alta heterogeneidade entre mercados. Além disso, observa-se que a adoção de veículos elétricos ainda é limitada na maioria dos países, com poucos mercados apresentando alta participação. Variáveis econômicas e regulatórias mostram distribuição mais equilibrada, enquanto fatores como crescimento e subsídios apresentam elevada variabilidade.

A análise estatística descritiva permitiu identificar medidas centrais e de dispersão das variáveis, fornecendo uma visão geral dos dados. No entanto, a análise gráfica revelou padrões mais complexos que não são capturados apenas por estatísticas resumidas, como a forte assimetria das distribuições, a presença de múltiplos outliers estruturais e a existência de possíveis grupos distintos de países (multimodalidade). Esses aspectos evidenciam a heterogeneidade do dataset e reforçam a necessidade de abordagens analíticas mais cuidadosas, como transformações de variáveis e segmentação dos dados.

## **4.5 Matrizes de correlação**
"""

#Correlacao de pearson
dataset.corr(method='pearson', numeric_only=True)

"""**Findings**
   1. Market Share de Veículos Elétricos (*ev_market_share*)
*   Correlações relevantes *ev_market_share* com:\
*is_ev_dominant* = 0.71 (forte)\
*emission_regulation_score* = 0.59\
*fuel_price_usd_per_liter* = 0.55\
*avg_ev_range_km* = 0.55\
*year* = 0.49\
*fast_chargers_share* = 0.46\
*gdp_per_capita* = 0.41
*   **Insights:** A adoção de veículos elétricos está mais associada a fatores regulatórios, tecnológicos e econômicos do que ao volume absoluto de vendas ou tamanho do mercado

   2. Infraestrutura (*charging_stations* e *fast_chargers_share*)
*   Correlação com *ev_market_share*:\
*charging_stations* = 0.21\
*fast_chargers_share* = 0.46
*   Correlação com *ev_sales*:\
*charging_stations* = 0.82
*   **Insights:** Não está tão correlacionada quanto esperado com a quantidade de estações de carga, mas melhor com a qualidade dos carregadores (se são mais rápidos). Esta segunda parece mais relevante.Infraestrutura acompanha volume, não a adoção relativa, ou seja, país maior tem vendas e mais estações de recarga, porém não necessáriamente um maior market share de veículos elétricos

   3. Economia e preços (*fuel_price*, *electricity_price*, *ev_subsidy* e *gdp_per_capita*)
*   Correlação com *ev_market_share*:\
*fuel_price* = 0.55\
*gdp_per_capita* = 0.41\
*electricity_price* = 0.21\
*ev_subsidy* = -0.06
*   **Insights:** Preço do combustível sobe e o market share de EV sobe, PIB sobre e o market share de EV também sobe. EV se torna mais viável quando: combustível é mais caro e quando a renda é mais alta. Preço da eletricidade e subsídios são fatores que influenciam pouco

   4. Influência do tempo (*year*)
*   Correlação com *year*:\
*avg_ev_range_km* = 0.97\
*fast_chargers_share* = 0.78\
*ev_market_share* = 0.49
*   **Insights:** O crescimento de EV é fortemente temporal (tecnologia + maturidade)

   5. Energia e economia (*fuel_price*, *gdp_per_capita*, *ev_market_share* e *emission_regulation*)
*   Correlação com *fuel_price*:\
*ev_market_share* = 0.55\
*emission_regulation* = 0.82
*   Correlação com *gdp_per_capita*:\
*emission_regulation* = 0.66
*   **Insights:** Países mais ricos tem regulação mais forte, portanto, tem combustível caro e um maior share de veículos elétricos

   6. Crescimento ano a ano do número de veículos elétricos (*ev_growth_rate_yoy*)
*   **Insights:** Quase nenhuma correlação com nada. Não é boa variável preditiva

   7. Dominância dos veículos elétricos (*is_ev_dominant*)
*   Correlação com *is_ev_dominant*:\
*ev_market_share* = 0.71\
*fuel_price* = 0.24\
*gdp* = 0.24
*   **Insights:** Dominância EV depende principalmente de fatores estruturais

**Sumário**
   
A análise de correlação revelou que a adoção de veículos elétricos está mais fortemente associada a fatores estruturais como nível de regulação ambiental, preço do combustível, desenvolvimento econômico e evolução tecnológica, do que a fatores isolados como subsídios ou número absoluto de estações de recarga. Além disso, observou-se forte multicolinearidade entre variáveis de volume de vendas, indicando redundância de informação. Esses resultados sugerem que a transição para veículos elétricos depende de um conjunto integrado de condições econômicas, tecnológicas e regulatórias (depende de um ecossistema).

**Observações:**

*  **Atributos importantes:**\
   *fuel_price*\
   *gdp_per_capita*\
   *emission_regulation_score*\
   *avg_ev_range_km*\
   *fast_chargers_share*

*  **Atributos menos úteis:**\
   *ev_growth_rate_yoy*\
   *ev_subsidy_usd (isoladamente)*

*  **Variáveis problemáticas:**\
   *total_vehicle_sales*\
   *petrol_car_sales*\
   *diesel_car_sales*

## **4.6 Análise do Target**
"""

#Análise do target
TARGET = "ev_market_share"
PROBLEM_TYPE = "serie_temporal"
DATE_COLUMN = "year"

print(f"Target: {TARGET}")
print(f"Tipo de problema: {PROBLEM_TYPE}\n")

print("Estatísticas descritivas do target:")
display(dataset[TARGET].describe().round(4).to_frame("ev_market_share (%)"))

print("\nDistribuição por faixa de adoção:")
bins   = [0, 1, 5, 15, 30, 50, 100]
labels = ["0–1% (embrionário)", "1–5% (emergente)", "5–15% (crescimento)", "15–30% (aceleração)", "30–50% (maturação)", "50–100% (dominante)"]
faixas = pd.cut(dataset[TARGET], bins=bins, labels=labels, include_lowest=True)
display(faixas.value_counts().sort_index().to_frame("contagem"))

print("\nTarget do Brasil ao longo do tempo:")
brasil = (dataset[dataset["country"] == "Brazil"]
          .groupby(DATE_COLUMN)[TARGET]
          .mean()
          .round(3)
          .to_frame("share médio (%)"))
display(brasil)

"""**Findings**

A grande maioria dos países e segmentos analisados ainda vende muito poucos carros elétricos. Mais da metade está praticamente no começo dessa transição e só um punhado de lugares, como a Noruega, já chegou perto de ter mais elétricos do que carros a combustão vendidos. Ou seja, no mundo todo, essa mudança ainda está em estágio inicial na maior parte dos lugares, com poucos "campeões" puxando a média para cima.

No Brasil, o padrão é claro: durante praticamente uma década (2010 a 2020) quase não havia carros elétricos sendo vendidos. A partir de 2021, as vendas começaram a decolar de verdade, crescendo bastante ano após ano até 2023. Nos últimos dois anos esse crescimento continua forte, mas num ritmo um pouco mais estável, como se o país tivesse saído da largada e agora estivesse ganhando velocidade de forma mais constante.

Mesmo com esse crescimento expressivo nos últimos anos, o Brasil ainda está bem atrás da maioria dos outros países do estudo: hoje cerca de 1 em cada 25 carros novos é elétrico por aqui, enquanto em países líderes essa proporção passa de 1 em cada 3 ou até 1 em cada 2. Isso bate com o que já tínhamos visto antes: o Brasil ainda não tem todas as condições (regulação ambiental forte, combustível muito caro, renda alta) que os países mais avançados nessa transição já possuem.

Por fim, esse comportamento de "quase zero por muito tempo e depois disparada" traz um cuidado importante para qualquer previsão: como o Brasil tem poucos anos de dados em que o crescimento já estava acelerado, é arriscado prever com muita certeza quando os elétricos vão "dominar" o mercado brasileiro.
"""

#Análise exploratória visual do target
TARGET = "ev_market_share"
PROBLEM_TYPE = "serie_temporal"
DATE_COLUMN = "year"

numeric_cols = dataset.select_dtypes(include=np.number).columns.tolist()
categorical_cols = dataset.select_dtypes(exclude=np.number).columns.tolist()
numeric_features = [c for c in numeric_cols if c != TARGET and c != DATE_COLUMN]

#Distribuicao do target por faixa
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

dataset[TARGET].hist(bins=40, ax=axes[0], color="#378ADD")
axes[0].set_title("Distribuição EV Market Share")
axes[0].set_xlabel(" Share EV (%)")
axes[0].set_ylabel("Frequência")

np.log1p(dataset[TARGET]).hist(bins=40, ax=axes[1], color="#378ADD")
axes[1].set_title("Distribuição EV Market Share (Log)")
axes[1].set_xlabel("log(Share EV (%))")
axes[1].set_ylabel("Frequência")

plt.show()

"""**Findings**

Olhamos o quanto as vendas de carros elétricos variam entre os diferentes países e anos, e descobrimos que a maioria dos casos está concentrada em números bem baixos (perto de 0%), enquanto pouquíssimos lugares (como a Noruega) têm números muito altos. Isso cria um desequilíbrio: se a gente tentasse "ensinar" um modelo de previsão com esses dados do jeito que estão, ele acabaria prestando atenção demais nesses poucos casos extremos e ignorando o padrão mais comum, que é justamente o que mais se parece com a situação do Brasil hoje.

Para resolver isso, testamos aplicar uma transformação matemática (log) que basicamente "achata" essa diferença faz com que os números muito altos não pesem tanto e os números baixos fiquem mais fáceis de comparar entre si. Funcionou bem: depois da transformação, os dados ficaram bem mais equilibrados e mais fáceis de um modelo aprender com eles.

Só que tem um detalhe importante: mesmo depois de "achatar" os dados, ainda existe um monte de casos exatamente em zero ou muito perto disso (países que praticamente não venderam carros elétricos ainda). Nenhuma das duas versões resolve totalmente a quantidade de zeros e é justamente essa fase de transição entre "ainda não começou" e "começou a crescer" que é a mais importante para entender o momento do Brasil.
"""

#Evolução temporal do share EV por segmento no Brasil
brasil = dataset[dataset["country"] == "Brazil"]

fig, ax = plt.subplots(figsize=(5, 4))
for seg, grp in brasil.groupby("vehicle_segment"):
    ax.plot(grp[DATE_COLUMN], grp[TARGET], marker="o", label=seg)

ax.axhline(50, color="#D85A30", linestyle="--", linewidth=1.2, label="Paridade (50%)")
ax.set_title("Evolução do share EV no Brasil por segmento")
ax.set_xlabel("Ano")
ax.set_ylabel("Share EV (%)")
ax.legend()
plt.tight_layout()
plt.show()

"""**Findings**

O gráfico mostra como a fatia de carros elétricos no Brasil cresceu ao longo dos anos, separando por três tipos de veículo: comerciais, populares (mass market) e premium.

A primeira coisa que salta aos olhos é a linha pontilhada laranja em cima, marcando os 50%, e esse é o ponto em que os elétricos teriam "tomado a dianteira" dos carros a combustão (paridade). E o que se obserca é que, até 2025, nenhuma das três linhas chega nem perto disso: elas ficam perto de zero no gráfico até 2020 e só começam a subir de forma visível a partir de 2021/2022.

Ao avaliar os números reais por trás do gráfico: em 2025, o segmento premium tem cerca de 5,8% de carros elétricos, o popular (mass market) tem cerca de 4%, e o comercial fica em torno de 1,4%, ou seja, carros elétricos de luxo estão crescendo um pouco mais rápido que os populares, e os comerciais (caminhões, vans, frotas) estão bem mais atrasados. Isso faz sentido, já que veículos comerciais costumam ter exigências de autonomia e custo diferentes dos carros de passeio.

Em resumo: o Brasil está numa fase bem inicial dessa transição em todos os tipos de veículo, com crescimento mais visível só nos últimos 3-4 anos, e ainda muito distante da linha de paridade de 50%, especialmente no segmento comercial, que é o que está mais atrasado.
"""

#Correlação dos atributos numéricos com o target
corr = (dataset[numeric_features + [TARGET]]
        .corr()[TARGET]
        .drop(TARGET)
        .sort_values(ascending=False))

fig, ax = plt.subplots(figsize=(6, 6))
corr.plot(kind="bar", ax=ax, color=["#378ADD" if v >= 0 else "#D85A30" for v in corr])
ax.set_title("Correlação dos Atributos com EV Market Share")
ax.set_xlabel("Feature")
ax.set_ylabel("Correlação de Pearson")
ax.axhline(0, color="gray", linewidth=0.8)

plt.show()

"""**Findings**

O gráfico confirma que a adoção de carros elétricos no Brasil (e no mundo) está muito mais ligada a condições estruturais do país, como a regulação ambiental forte, combustível caro, carros com mais autonomia, tecnologia mais madura e renda alta do que, efetivamente, a incentivos isolados como subsídio em dinheiro. Ou seja, não é uma única política que vai "destravar" o mercado de elétricos. É a combinação de vários fatores econômicos, tecnológicos e regulatórios acontecendo ao mesmo tempo. Isso reforça a ideia central já vista antes: a virada para os elétricos depende de um conjunto de condições.
"""

#Distribuição dos atributos numéricos mais relevantes
top_features = corr.abs().sort_values(ascending=False).head(6).index.tolist()

fig, axes = plt.subplots(2, 3, figsize=(12, 8))
for ax, col in zip(axes.flatten(), top_features):
    dataset[col].hist(bins=30, ax=ax, color="#378ADD")
    ax.set_title(col)
    ax.set_xlabel("")
    ax.set_ylabel("Frequência")

plt.suptitle("Distribuição das 6 atributos mais correlacionados com o target", y=1.01)

plt.show()

"""**Findings**

O histograma de *is_ev_dominant* mostra uma variável quase toda concentrada em 0, com pouquíssimos 1 (~1,8% da base | coerentemente igual à faixa "dominante" que vimos na análise do target). Isso é um sinal forte de que *is_ev_dominant* não é um atributo independente, e sim uma versão binarizada do próprio *ev_market_share*. Se for esse o caso, a correlação de 0,71 não representa uma relação causal nova, mas sim parcialmente um vazamento de informação do target (data leakage). Essa variável não será usada como preditor em um modelo que tenta prever *ev_market_share*.
"""

#Distribuição da variável categórica vehicle_segment
fig, ax = plt.subplots(figsize=(6, 3))
dataset["vehicle_segment"].value_counts().plot(kind="bar", ax=ax, color="#378ADD")
ax.set_title("Contagem por segmento de veículo")
ax.set_xlabel("Segmento")
ax.set_ylabel("Contagem")

plt.show()

"""**Findings**

O gráfico mostra que *vehicle_segment* tem três categorias (commercial, mass_market, premium), cada uma com exatamente 400 observações (33,3%), ou seja, um painel perfeitamente balanceado decorrente do desenho do dataset (25 países x 16 anos x 3 segmentos = 1.200 linhas), e não de um padrão de mercado real.

Essa contagem responde apenas uma pergunta: "a amostra está bem distribuída entre as categorias?". A resposta é sim, o que é positivo do ponto de vista de robustez estatística (nenhuma categoria terá estimativas instáveis por falta de dados). Mas esse resultado não diz nada sobre a relevância de *vehicle_segment* para o modelo, nem sobre "dominância" de um segmento em adoção de elétricos e essa não é, de fato, uma pergunta que o problema propõe responder, já que a divisão em segmentos foi artificialmente balanceada por construção do painel, não observada organicamente no mercado.

## **4.7 Síntese da análise exploratória**

A análise exploratória do dataset de adoção de veículos elétricos confirma que o fenômeno estudado está, em sua maior parte, em estágio inicial de difusão. O target *ev_market_share* é uma variável altamente assimétrica e zero-inflacionada: mais da metade das observações do painel está abaixo de 1% de participação, enquanto apenas um pequeno grupo de países líderes, como Noruega e Suécia, já ultrapassou metade do mercado. Essa forma de distribuição, com cauda longa e concentração inicial, é consistente com o comportamento esperado de uma curva de difusão tecnológica em formato S.

A trajetória brasileira reforça esse diagnóstico: o país praticamente não teve vendas de elétricos entre 2010 e 2020, apresentou um ponto de inflexão claro a partir de 2021-2022 e, mesmo com crescimento acelerado nos últimos anos, chegou a 2025 com apenas 3,75% de share médio, ocupando a 22ª posição entre 25 países e ainda distante da linha de paridade de 50%. Esse atraso se repete de forma desigual entre os segmentos de veículo: o segmento premium lidera a adoção no Brasil, seguido pelo mass market, com o segmento comercial bem mais atrasado, refletindo diferenças de custo e exigência de autonomia entre esses nichos.

Em relação aos atributos explicativos, a análise de correlação identificou que a adoção de elétricos está mais associada a fatores estruturais como a regulação ambiental, preço do combustível, autonomia média da bateria, PIB per capita e maturidade tecnológica ao longo do tempo, do que a incentivos isolados como subsídio em dinheiro ou ao crescimento percentual ano a ano, que se mostraram fracos preditores diretos. Esse padrão sustenta a leitura de que a transição para elétricos depende de um conjunto integrado de condições econômicas, regulatórias e tecnológicas, e não de uma única alavanca de política pública isolada.

Do ponto de vista de qualidade e estrutura dos dados, o painel não tem valores ausentes ou duplicatas e é balanceado por país (48 linhas por país) e segmento (400 linhas por categoria). Por outro lado, a distribuição por região é desigual. A Europa concentra mais da metade das observações, e o Brasil é o único representante da América do Sul no painel, o que limita a aplicação direta de uma estratégia de "países vizinhos". A exploração também revelou dois cuidados metodológicos importantes para a etapa de modelagem: a variável *is_ev_dominant* constitui um vazamento de dados, por ser derivada deterministicamente de um limiar do próprio target, e deve ser excluída do conjunto de preditores; e variáveis de volume absoluto (*total_vehicle_sales*, *petrol_car_sales* e *diesel_car_sales*) mostraram correlação pouco informativa ou redundante, exigindo seleção criteriosa de features.

Em conjunto, esses achados moldam a estratégia de modelagem: um ajuste de curva de difusão não-linear para responder diretamente à pergunta de quando o Brasil atinge a paridade, complementado por modelos de regressão (preferencialmente baseados em árvore, menos sensíveis à escala heterogênea das variáveis e à assimetria do target) para quantificar o ganho preditivo das covariáveis externas e testar a transferência de padrões entre países, sempre com as devidas correções de pré-processamento: padronização de escala, exclusão de variáveis com vazamento e tratamento específico da concentração de casos próximos a zero, que representa exatamente a fase em que o mercado brasileiro se encontra hoje.

# **5. Preparação dos dados e divisão treino/teste**

**Separação entre features e target**

O target é *ev_market_share*, a variável contínua que representa a fatia de mercado de veículos elétricos em cada país, segmento e ano. As features são todas as demais colunas do dataset, exceto as excluídas por critérios técnicos descritos abaixo.

**Remoção de colunas**

Oito colunas foram removidas do conjunto de preditores, agrupadas em três motivos:

- **Leakage direto**: *is_ev_dominant* é derivada deterministicamente do target (limiar de 50%) e *co2_emissions_transport_mt* é consequência da adoção de elétricos, não causa, pois ambas só existem depois que o target já é conhecido.
- **Relação matemática com o target**: *ev_sales* e *ev_growth_rate_yoy* têm relação direta com *ev_market_share*.
- **Redundância e multicolinearidade**: *petrol_car_sales* e *diesel_car_sales* são componentes diretos de *total_vehicle_sales* (que permanece no modelo); *avg_ev_range_km* é praticamente colinear com *year* (correlação 0,97) e não acrescenta poder preditivo específico ao Brasil; *powertrain_type* tem variância zero (todos os registros são ICE).

Além disso, *country* e *region* foram tratadas como identificadores de grupo (não preditores), e *year* como variável temporal da série.

**Engenharia de lags**

Antes de qualquer divisão, foram criados lags de 1, 2 e 3 anos para *ev_market_share*, *ev_sales* e *ev_growth_rate_yoy*, além de uma feature de aceleração (*ev_share_accel = lag1 - lag2*), que captura se o crescimento está se intensificando ou desacelerando. Os lags foram calculados dentro de cada grupo *country* x *vehicle_segment* via *shift*, garantindo que nunca há mistura de séries distintas. As primeiras linhas de cada série (sem histórico suficiente para gerar o lag de 3 anos) foram descartadas via *dropna*, reduzindo o dataset de 1.200 para 975 linhas — perda esperada e sem impacto na qualidade dos dados.

**Divisão treino/validação/teste**

Por se tratar de um problema de série temporal, a divisão foi feita por corte cronológico estrito, sem embaralhamento:

- **Treino**: 2013–2022 (750 linhas, ~77%) período usado para ajustar os modelos
- **Validação**: 2023–2024 (150 linhas, ~15%) período usado usado para comparar modelos e ajustar parâmetros
- **Teste**: 2025 (75 linhas, ~8%) reservado para avaliação final, simulando previsão do ano mais recente

Essa abordagem garante que o modelo nunca veja dados futuros durante o treino, respeitando a causalidade temporal. Como o painel é balanceado (25 países x 3 segmentos = 75 linhas por ano), todos os países e segmentos estão representados em todos os três conjuntos, sem risco de avaliar o modelo em combinações que ele nunca viu.
"""

#Configuração do problema
TARGET = "ev_market_share"
PROBLEM_TYPE = "serie_temporal"

#Identificadores de grupo, não preditores
ID_COLUMNS = ["country", "region"]

#Eixo temporal da série
DATE_COLUMN = "year"

DROP_COLUMNS = ["powertrain_type","diesel_car_sales","petrol_car_sales","co2_emissions_transport_mt","is_ev_dominant","avg_ev_range_km","ev_sales","ev_growth_rate_yoy"]

assert TARGET in dataset.columns, "Defina um TARGET válido."

columns_to_exclude = set(ID_COLUMNS + DROP_COLUMNS + [DATE_COLUMN, TARGET])

features = [c for c in dataset.columns if c not in columns_to_exclude]
print("Tipo de problema  :", PROBLEM_TYPE)
print("Target            :", TARGET)
print("Coluna de data    :", DATE_COLUMN)
print("Número de features:", len(features))
print("Features          :", features)

#Divisão dos dados
assert DATE_COLUMN in dataset.columns, "Defina DATE_COLUMN para séries temporais."

#Engenharia de lags
dataset = dataset.sort_values(["country", "vehicle_segment", DATE_COLUMN]).copy()

lag_source_cols = ["ev_market_share", "ev_sales", "ev_growth_rate_yoy"]
for col in lag_source_cols:
    for lag in [1, 2, 3]:
        dataset[f"{col}_lag{lag}"] = (
            dataset.groupby(["country", "vehicle_segment"])[col].shift(lag)
        )

dataset["ev_share_accel"] = dataset["ev_market_share_lag1"] - dataset["ev_market_share_lag2"]

#Remove linhas sem histórico suficiente (primeiros anos de cada série)
dataset = dataset.dropna(subset=[c for c in dataset.columns if "_lag" in c or c == "ev_share_accel"])

#Adiciona as novas features ao conjunto
lag_features = [c for c in dataset.columns if "_lag" in c or c == "ev_share_accel"]
all_features = features + lag_features

#Cortes cronológicos por ano
TRAIN_END = 2022
VAL_END   = 2024

#Teste = 2025 (tudo acima de VAL_END)

train_dataset = dataset[dataset[DATE_COLUMN] <= TRAIN_END]
val_dataset   = dataset[(dataset[DATE_COLUMN] > TRAIN_END) & (dataset[DATE_COLUMN] <= VAL_END)]
test_dataset  = dataset[dataset[DATE_COLUMN] > VAL_END]

X_train = train_dataset[all_features].copy()
y_train = train_dataset[TARGET].copy()

X_val   = val_dataset[all_features].copy()
y_val   = val_dataset[TARGET].copy()

X_test  = test_dataset[all_features].copy()
y_test  = test_dataset[TARGET].copy()

#Resumo
print(f"Anos no treino:     {sorted(train_dataset[DATE_COLUMN].unique())}")
print(f"Anos na validação:  {sorted(val_dataset[DATE_COLUMN].unique())}")
print(f"Anos no teste:      {sorted(test_dataset[DATE_COLUMN].unique())}")
print()
print(f"X_train: {X_train.shape} | y_train: {y_train.shape}")
print(f"X_val:   {X_val.shape}   | y_val:   {y_val.shape}")
print(f"X_test:  {X_test.shape}  | y_test:  {y_test.shape}")
print()
print(f"Total de features: {len(all_features)}")
print(f"Features originais: {features}")
print(f"Features de lag:    {lag_features}")

"""# **6. Pré-processamento e pipeline**

## **6.1 Conversão de Atributos**

**Converter Atributos CategóricosOr**
- Converter *vehicle_segment* para category

**Motivo:**
- Modelos não interpretam texto diretamente
- Conversão para category reduz uso de memória e sinaliza semanticamente que a variável é nominal, não ordinal
- *country* e *region* são identificadores de grupo e não entram como preditores, então não precisam ser convertidas para uso no modelo
"""

#Conversao para category
dataset["vehicle_segment"] = dataset["vehicle_segment"].astype("category")

#Categorização ordinal de vehicle_segment
segment_order = {"commercial": 0, "mass_market": 1, "premium": 2}

#Aplicar se 'vehicle_segment' já nao é numerico
if not pd.api.types.is_numeric_dtype(X_train["vehicle_segment"]):
    X_train["vehicle_segment"] = X_train["vehicle_segment"].map(segment_order).astype(int)
    X_val["vehicle_segment"]   = X_val["vehicle_segment"].map(segment_order).astype(int)
    X_test["vehicle_segment"]  = X_test["vehicle_segment"].map(segment_order).astype(int)
else:
    print("vehicle_segment columns are already numeric. Skipping re-mapping.")

"""## **6.2 Transformação de Atributos**

**Transformar Atributos com Alta Assimetria**
- Aplicar log1p em: *charging_stations*, *gdp_per_capita*, *ev_subsidy_usd* e nas colunas de lag de *ev_sales* (*ev_sales_lag1*, *ev_sales_lag2*,*ev_sales_lag3*)

**Motivo:**
- Essas variáveis têm distribuições com cauda longa e ranges muito amplos (ex: *charging_stations* vai de 0 a 4,3 milhões)
- log1p comprime a escala sem descartar zeros, reduzindo a influência de outliers extremos no ajuste do modelo
"""

#Transformar atributos com alta assimetria (log1p)
log_cols = ["charging_stations","gdp_per_capita","ev_subsidy_usd","ev_sales_lag1","ev_sales_lag2","ev_sales_lag3"]

for col in log_cols:
    dataset[col] = np.log1p(dataset[col])

"""## **6.3 Padronização de Atributos**

**Padronizar Atributos Numéricos**
- Aplicar StandardScaler em: *charging_stations*, *gdp_per_capita*, *ev_subsidy_usd*, *fuel_price_usd_per_liter*, *electricity_price_usd_per_kwh*, *urban_population_percent*, *emission_regulation_score*, *fast_chargers_share* e todos os lags numéricos

**Motivo:**
- Variáveis em escalas muito diferentes coexistem no dataset (de decimais como *electricity_price* até milhões como *charging_stations*)
"""

#Padronizar atributos numéricos (StandardScaler)
scale_cols = ["charging_stations","gdp_per_capita","ev_subsidy_usd","fuel_price_usd_per_liter","electricity_price_usd_per_kwh","urban_population_percent","emission_regulation_score","fast_chargers_share","ev_sales_lag1", "ev_sales_lag2", "ev_sales_lag3","ev_market_share_lag1", "ev_market_share_lag2", "ev_market_share_lag3","ev_growth_rate_yoy_lag1", "ev_growth_rate_yoy_lag2", "ev_growth_rate_yoy_lag3","ev_share_accel"]

scaler = StandardScaler()

X_train[scale_cols] = scaler.fit_transform(X_train[scale_cols])
X_val[scale_cols]   = scaler.transform(X_val[scale_cols])
X_test[scale_cols]  = scaler.transform(X_test[scale_cols])

"""## **6.4 Criação de Novos Atributos**

**Criar Atributos Derivados**
- *price_ratio* = *fuel_price_usd_per_liter* / *electricity_price_usd_per_kwh* | razão entre custo do combustível e da eletricidade, proxy direto da vantagem econômica do elétrico

**Motivo:**
- *price_ratio* sintetiza em uma única variável a competitividade econômica do elétrico frente ao combustível. Quanto maior a razão, mais vantajoso o elétrico em custo operacional, o que se mostra fator mais relevante na análise de correlação
"""

#Criar atributos derivados

# Razão entre preço do combustível e da eletricidade
dataset["price_ratio"] = (dataset["fuel_price_usd_per_liter"] / dataset["electricity_price_usd_per_kwh"])

"""## **6.5 Remoção de Atributos**

**Remover Atributos**
- Remover *total_vehicle_sales* do conjunto de features

**Motivo:**
- Correlação quase nula com o target (0,006), sem poder preditivo relevante identificado na AED
- Representa volume absoluto de mercado, que não se mostrou associado à adoção relativa de elétricos
"""

#Remover total_vehicle_sales
dataset = dataset.drop(columns=["total_vehicle_sales"])
features = [f for f in features if f != "total_vehicle_sales"]

"""# **7. Baseline e modelos candidatos**

Para avaliar se os modelos realmente aprenderam padrões relevantes sobre a adoção de veículos elétricos, a estratégia de modelagem começa por uma solução de referência simples, o baseline, e avança progressivamente para abordagens mais sofisticadas.

O baseline utilizado é a predição ingênua pelo último valor conhecido: prever o share de elétricos de um país em determinado ano usando o valor do ano anterior. Essa é a solução mais simples possível para uma série temporal e serve como piso mínimo de desempenho. Qualquer modelo que não consiga superá-la não aprendeu nada útil sobre os dados.

A partir dessa referência, são treinados três modelos candidatos em ordem crescente de complexidade.

1. A Regressão Linear, como algoritmo base para problemas de regressão, é incluída para verificar se as relações entre as variáveis são suficientemente diretas para um modelo simples capturar, sendo avaliada pelas métricas MSE, RMSE e R² conforme orientação da disciplina.

2. O Random Forest, como o principal exemplo de ensemble do tipo bagging, é incluído por sua capacidade de capturar relações não-lineares e por ser robusto à diferença de escala entre as variáveis, que são características relevantes dado o perfil do dataset identificado na AED.

3. Por fim, o XGBoost, descrito em aula como uma das técnicas de ensemble mais sofisticadas disponíveis, é incluído por construir modelos em sequência onde cada um corrige os erros do anterior, tendendo a produzir resultados mais precisos que o Random Forest em dados com padrões sutis e complexos.

Os quatro modelos são comparados pelas métricas MAE, RMSE e R² no conjunto de validação (2023–2024), permitindo identificar qual abordagem melhor captura a trajetória de adoção de elétricos no painel de países analisado.
"""

#Definição de baseline e modelos candidatos
SEED = 42

baseline = {"Baseline (lag1)": None}

candidates = {
    "LinearRegression": LinearRegression(),
    "RandomForestRegressor": RandomForestRegressor(
        n_estimators=200,
        random_state=SEED,
        n_jobs=-1
    ),
    "XGBoostRegressor": XGBRegressor(
        n_estimators=200,
        learning_rate=0.05,
        random_state=SEED,
        n_jobs=-1
    )
}

print("Baseline    :", list(baseline.keys()))
print("Candidatos  :", list(candidates.keys()))

"""## **7.1 Justificativa dos modelos**

## Justificativa dos modelos escolhidos

**O baseline é coerente?**
Sim. Para séries temporais, a predição pelo último valor conhecido (lag1) é o baseline mais natural: ela captura a inércia da série pelo fato de que o share de elétricos de um país tende a ser próximo do ano anterior, sem usar nenhuma informação estrutural sobre preço de combustível, regulação ou renda. Qualquer modelo que não supere esse piso não aprendeu nada além do que já estava contido no histórico imediato da própria série.

**Os modelos candidatos são adequados ao tipo e tamanho dos dados?**
Sim. O dataset tem 975 linhas após a engenharia de lags, features de natureza mista (numéricas contínuas, ordinais e lags) e um target com distribuição assimétrica, perfil que favorece modelos baseados em árvore. A Regressão Linear entra como referência interpretável: se não superar o baseline, confirma que a dinâmica de adoção é não-linear, algo já sugerido pelo formato de curva S identificado na AED. O Random Forest e o XGBoost são adequados ao tamanho do dataset (nem grande o suficiente para exigir redes neurais, nem pequeno o suficiente para limitar ensembles) e lidam naturalmente com as não-linearidades e com a heterogeneidade de escala das features.

**Algum modelo exige tratamento específico?**
A Regressão Linear é o único modelo do conjunto sensível à escala das variáveis e essa necessidade já foi endereçada na etapa de pré-processamento, onde o StandardScaler foi aplicado exclusivamente sobre o conjunto de treino e replicado na validação e no teste. Random Forest e XGBoost são invariantes a escala por construção, então a padronização não os afeta positivamente nem negativamente. A codificação ordinal de *vehicle_segment* (commercial=0, mass_market=1, premium=2) é compatível com os três modelos.

**Há restrições de interpretabilidade, tempo ou custo computacional?**
O custo computacional dos três modelos é baixo para o tamanho do dataset, uma vez que o treinamento completo ocorre em segundos. Em relação à interpretabilidade, a Regressão Linear é o modelo mais transparente, enquanto Random Forest e XGBoost são modelos de "caixa-preta", mas ambos oferecem feature importance nativa, o que é suficiente para uma primeira leitura de quais variáveis o modelo considera relevantes.

# **8. Treinamento e avaliação inicial**
"""

#Garantia da ordem de execução (commercial=0, mass_market=1, premium=2), independente da ordem das células
segment_order = {"commercial": 0, "mass_market": 1, "premium": 2}
for dataset in [X_train, X_val, X_test]:
    if X_train["vehicle_segment"].dtype == object:
        dataset["vehicle_segment"] = dataset["vehicle_segment"].map(segment_order)

#Dicionarios para armazenar resultados e modelos treinados
results       = {}
trained_models = {}

# Função de avaliação para regressao
# Calcula MAE, RMSE e R²
def evaluate_regression(y_true, y_pred):
    mae  = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2   = r2_score(y_true, y_pred)
    return {"MAE": round(mae, 4), "RMSE": round(rmse, 4), "R²": round(r2, 4)}

#Baseline: predição ingenua pelo último valor conhecido (lag1)
y_pred_baseline = X_val["ev_market_share_lag1"]
results["Baseline (lag1)"] = evaluate_regression(y_val, y_pred_baseline)
results["Baseline (lag1)"]["train_time_s"] = 0.0  # sem treinamento
trained_models["Baseline (lag1)"] = None

#Modelos candidatos treinados em 2013–2022, avaliados em 2023–2024
for name, model in candidates.items():

    #Treina o modelo com os dados históricos (X_train, y_train)
    t0 = time.time()
    model.fit(X_train, y_train)
    train_time = round(time.time() - t0, 3)

    #Gera previsoes para o conjunto de validação (2023–2024)
    y_pred = model.predict(X_val)

    #Avalia o modelo e registra o tempo de treinamento
    results[name] = evaluate_regression(y_val, y_pred)
    results[name]["train_time_s"] = train_time

    #Armazena o modelo treinado para uso posterior (análise de importância, previsao final)
    trained_models[name] = model

    print(f"{name} treinado em {train_time}s — RMSE: {results[name]['RMSE']}")

#Tabela comparativa dos modelos
dataset_results = pd.DataFrame(results).T.sort_values("RMSE")
display(dataset_results)

"""## **8.1 Análise dos resultados iniciais**

**Todos os três modelos superaram o baseline com folga.** O baseline (lag1) apresentou RMSE de 22.67 e R² negativo (-0.47), confirmando que a simples repetição do valor do ano anterior é insuficiente para capturar a dinâmica de crescimento do mercado de elétricos, resultado esperado dado o ritmo de aceleração identificado na AED, especialmente a partir de 2021. O fato de todos os candidatos superarem o baseline com tanta margem indica que as features estruturais (regulação, preço de combustível, PIB, lags) carregam informação real e relevante sobre a trajetória de adoção.

**As métricas escolhidas são adequadas, mas complementares.** O RMSE é a métrica principal por penalizar mais os erros grandes, o que é relevante num dataset onde países como Noruega e Suécia puxam a cauda superior da distribuição. O MAE complementa por ser mais robusto a esses outliers e mais interpretável para o objetivo do projeto: um MAE de 2.73 significa que o modelo erra, em média, 2.73 pontos percentuais de share, o que é razoável para um target que varia de 0% a 95%. O R² completa a leitura ao mostrar que os dois melhores modelos explicam cerca de 94% da variação do target, o que é consistente com a forte estrutura de correlação identificada na AED.

**O Random Forest apresenta sinais de overfitting.** Com RMSE de 6.37 e R² de 0.88, resultados significativamente piores que os outros dois candidatos, o modelo provavelmente ajustou bem os dados de treino (2013–2022) mas perdeu capacidade de generalizar para 2023–2024 (período em que o crescimento acelerou de forma diferente do histórico). Nenhum dos três modelos apresenta sinais evidentes de underfitting: todos têm R² acima de 0.88 e superam o baseline com margem expressiva, o que indica que os três conseguiram capturar os padrões dos dados.

**O tempo de treinamento é irrelevante como critério de decisão.** Com 975 linhas, todos os modelos treinaram em menos de 3 segundos: Regressão Linear em 0.036s, XGBoost em 1.6s e Random Forest em 2.8s. O tempo não representa nenhuma restrição prática para este MVP.

**Os resultados fazem sentido à luz da AED.** A Regressão Linear competindo de igual para igual com o XGBoost era um resultado plausível: a AED já havia mostrado correlações lineares fortes entre o target e variáveis como preço de combustível, regulação ambiental e PIB per capita, sugerindo que boa parte das relações nos dados é suficientemente direta para um modelo linear capturar. A pequena superioridade do XGBoost no RMSE (4.37 vs. 4.45) indica que há alguma não-linearidade residual que o boosting captura melhor, consistente com o formato de curva S da série temporal identificado na AED, que por natureza é não-linear. O baixo desempenho do Random Forest também é coerente: a AED mostrou que o crescimento acelerou bruscamente a partir de 2021, e modelos de bagging tendem a ser menos adaptáveis a mudanças de regime do que modelos de boosting sequencial.

# **9. Validação e otimização de hiperparâmetros**

Dos três modelos treinados, o XGBoost foi o que apresentou o menor RMSE na validação (4.37), ou seja, foi o que errou menos. Faz sentido, então, investir o esforço de otimização nele, ou seja, ajustar o modelo que já está na frente tem mais chance de produzir um resultado ainda melhor do que tentar melhorar um modelo que já mostrou ser mais fraco.

**Ajustes**

**Número de árvores** (*n_estimators*): quanto mais árvores, mais o modelo tem chances de corrigir seus próprios erros, mas chega um ponto em que adicionar mais árvores não melhora tanto o resultado e só aumenta o tempo de processamento. Testamos 100, 200 e 300 árvores.

**Taxa de aprendizado** (*learning_rate*): controla o quanto cada árvore nova tenta corrigir os erros da anterior. Uma taxa muito alta faz o modelo aprender rápido, mas pode pular a solução ideal. Uma taxa muito baixa aprende devagar, mas com mais precisão.

**Profundidade das árvores** (*max_depth*): define o quão detalhada cada árvore pode ser. Árvores muito profundas tendem a "decorar" os dados de treino sem conseguir generalizar para dados novos (overfitting).

**Escolha da melhor combinação**

Em vez de testar cada combinação uma única vez, o que poderia dar melhores ou piores resultados dependendo de qual pedaço dos dados foi usado, será usada uma técnica chamada **TimeSeriesSplit**, que divide o período de treino (2013–2022) em 5 janelas cronológicas. Em cada janela, o modelo treina nos anos anteriores e é avaliado nos anos seguintes, simulando exatamente o que aconteceria na prática. A combinação que produzir o menor RMSE médio ao longo dessas 5 janelas será declarada a melhor.

Isso garante que a escolha da melhor configuração foi feita de forma justa,usando só os dados de treino, sem acessar os dados de validação (2023–2024) ou de teste (2025). O conjunto de validação só entra depois, para confirmar se a melhora se mantém em dados que o modelo nunca viu durante o processo de otimização.
"""

#Numero de combinações testadas
N_ITER_SEARCH = 50

#Validacao cronologica
cv = TimeSeriesSplit(n_splits=5)

#Modelo a ser otimizado
model_to_tune = XGBRegressor(random_state=SEED, n_jobs=-1)

#Espaco de busca
param_dist = {
    "n_estimators"    : randint(100, 400),
    "learning_rate"   : uniform(0.01, 0.19),
    "max_depth"       : randint(3, 8),
    "subsample"       : uniform(0.6, 0.4),
    "colsample_bytree": uniform(0.6, 0.4)
}

#Metrica de avaliacao - neg_root_mean_squared_error: minimiza o RMSE
scoring = "neg_root_mean_squared_error"

#Busca aleatoria de hiperparametros
# RandomizedSearchCV testa N_ITER_SEARCH combinações aleatórias do espaço definido
# Mais eficiente que GridSearchCV quando o espaço de busca é grande
search = RandomizedSearchCV(
    estimator          = model_to_tune,
    param_distributions = param_dist,
    n_iter             = N_ITER_SEARCH,
    cv                 = cv,
    scoring            = scoring,
    random_state       = SEED,
    n_jobs             = 1,
    verbose            = 1
)

#Treina todas as combinações sobre o conjunto de treino (2013–2022)
search.fit(X_train, y_train)

#Resultados da busca
print("Melhor RMSE na validação cruzada :", round(-search.best_score_, 4))
print("Melhores hiperparâmetros          :", search.best_params_)

#Avalia o modelo otimizado na validacao (2023–2024)
best_xgb = search.best_estimator_
y_pred_best = best_xgb.predict(X_val)
results["XGBoost (otimizado)"] = evaluate_regression(y_val, y_pred_best)

#Comparação com o XGBoost padrao
dataset_comparison = pd.DataFrame({
    "XGBoost padrão"   : results["XGBoostRegressor"],
    "XGBoost otimizado": results["XGBoost (otimizado)"]
}).T
display(dataset_comparison)

#Armazena o modelo otimizado para a avaliação final no teste (2025)
trained_models["XGBoost (otimizado)"] = best_xgb

"""**Observação**

Na primeira tentativa, com 20 iterações, o resultado foi pior que o padrão. Alterando para 50 iterações, o XGBoost otimizado superou o padrão em todas as métricas.

O RMSE caiu de 4.37 para 4.29, uma redução pequena em termos absolutos, mas consistente com a melhora no MAE (de 3.11 para 3.03) e no R² (de 0.946 para 0.948). O modelo otimizado erra menos tanto nos casos comuns (MAE menor) quanto nos casos extremos (RMSE menor) e explica uma fração ligeiramente maior da variação do target.

A melhora é modesta, o que era esperado: o XGBoost padrão já estava bem calibrado para este dataset, e a margem de ganho com otimização era pequena desde o início. Ainda assim, a consistência da melhora nas três métricas ao mesmo tempo, sem que nenhuma piorasse, indica que a nova configuração é genuinamente melhor, não apenas uma variação aleatória.

## **9.1 Discussão da otimização**

**Resultado da otimização em relação modelo inicial**

Com 50 iterações, o XGBoost otimizado superou o padrão em todas as três métricas: RMSE caiu de 4.37 para 4.29, MAE de 3.11 para 3.03 e R² subiu de 0.946 para 0.948. A melhora é pequena em termos absolutos (menos de 0.1 ponto de RMSE), mas é consistente e real, já que nenhuma métrica piorou. Vale lembrar que na primeira tentativa com 20 iterações o resultado foi pior que o padrão, o que mostra que o número de iterações importa. Com poucas combinações testadas, a busca pode encontrar uma configuração ruim por acaso.

**Limitações**

Pelo tamanho do dataset (975 linhas), o custo computacional foi baixo. 50 iterações com 5 folds cada resultaram em 250 treinamentos, todos executados em segundos. A principal limitação foi de escopo: 50 iterações cobrem uma fração razoável do espaço de busca definido, mas estão longe de ser exaustivas. Com mais tempo, seria possível aumentar para 100 ou 200 iterações sem impacto prático no tempo de execução, o que aumentaria as chances de encontrar uma configuração ainda melhor.

**Escolha dos hiperparâmetros**

A configuração encontrada (*learning_rate* ≈ 0.15, *n_estimators* = 359, *max_depth* = 4, *subsample* ≈ 0.67, *colsample_bytree* ≈ 0.67) é coerente: uma taxa de aprendizado moderadamente alta (0.15) é compensada por um número maior de árvores (359), garantindo que o modelo corrija bem seus erros sem precisar de um aprendizado muito lento. A profundidade 4 é conservadora, evitando árvores muito complexas que tenderiam a decorar os dados de treino. Os valores de *subsample* e *colsample_bytree* em torno de 0.67 introduzem aleatoriedade controlada em cada árvore, o que ajuda a reduzir overfitting sem sacrificar poder preditivo, gerando resultado coerente com o perfil do dataset identificado na AED, onde o Random Forest sofreu de overfitting.

**Outros testes**

1. Aumentaria *N_ITER_SEARCH* para 100 ou 200 para cobrir melhor o espaço de busca e ter mais confiança de que a configuração encontrada é de fato a melhor.
2. Incluiria o hiperparâmetro *min_child_weight*, que controla o número mínimo de observações em cada folha da árvore e é especialmente relevante para datasets com zero-inflação como esse, onde muitos países ainda estão em share próximo de zero.
3. Testaria a Regressão Linear com regularização Ridge ou Lasso, variantes que adicionam uma penalidade para coeficientes muito grandes e que poderiam melhorar a generalização do modelo linear, especialmente dado que identificamos multicolinearidade entre algumas features na AED.

# **10. Avaliação final no conjunto de teste**
"""

#Avaliacao final do conjunto de teste (2025)
# O teste só é usado aqui, na avaliação final, após todas as decisões de modelagem terem sido tomadas com base na validação (2023–2024)

#Selecao do modelo final
#XGBoost otimizado foi escolhido
if search is not None and hasattr(search, "best_estimator_"):
    final_model      = search.best_estimator_
    final_model_name = "XGBoost (otimizado)"
else:
    final_model_name = "XGBoostRegressor"
    final_model      = trained_models[final_model_name]

print("Modelo final selecionado:", final_model_name)

#Previsão no conjunto de teste (2025)
y_pred_test = final_model.predict(X_test)

#Metricas finais
metrics_test = evaluate_regression(y_test, y_pred_test)
display(pd.DataFrame([metrics_test], index=[final_model_name]))

#Comparação completa: validação vs. teste
dataset_final_comparison = pd.DataFrame({
    "Validação (2023–2024)": results["XGBoost (otimizado)"],
    "Teste (2025)"         : metrics_test
}).T[["MAE", "RMSE", "R²"]]
print("\nComparação validação vs. teste:")
display(dataset_final_comparison)

#Grafico 1: valores reais vs. previstos ao longo do tempo
#Mostra visualmente se o modelo acompanha a trajetória real do share de elétricos
test_dataset_plot = test_dataset.copy()
test_dataset_plot["y_pred"] = y_pred_test

plt.figure(figsize=(10, 4))
for country in test_dataset_plot["country"].unique():
    subset = test_dataset_plot[test_dataset_plot["country"] == country]
    plt.plot(subset[DATE_COLUMN], subset[TARGET],  "o-",  alpha=0.4, color="steelblue")
    plt.plot(subset[DATE_COLUMN], subset["y_pred"], "x--", alpha=0.4, color="tomato")

plt.title("Real (azul) vs. Previsto (vermelho) — conjunto de teste 2025")
plt.xlabel("Ano")
plt.ylabel("EV Market Share (%)")
plt.tight_layout()
plt.show()

#Grafico 2: resíduos vs. valores previstos
residuals = y_test - y_pred_test

plt.figure(figsize=(8, 4))
plt.scatter(y_pred_test, residuals, alpha=0.5, color="steelblue")
plt.axhline(0, linestyle="--", color="tomato", linewidth=1)
plt.title("Resíduos vs. valores previstos — conjunto de teste 2025")
plt.xlabel("Valor previsto")
plt.ylabel("Resíduo (real − previsto)")
plt.tight_layout()
plt.show()

#Grafico 3: trajetoria do Brasil real vs. previsto
brasil_test = test_dataset_plot[test_dataset_plot["country"] == "Brazil"]

plt.figure(figsize=(8, 4))
plt.plot(brasil_test[DATE_COLUMN], brasil_test[TARGET],  "o-",  label="Real",    color="steelblue")
plt.plot(brasil_test[DATE_COLUMN], brasil_test["y_pred"], "x--", label="Previsto", color="tomato")
plt.title("Brasil — Real vs. Previsto (2025)")
plt.xlabel("Ano")
plt.ylabel("EV Market Share (%)")
plt.legend()
plt.tight_layout()
plt.show()

#Prepara o datataset de teste com previsões
test_dataset_plot = test_dataset.copy()
test_dataset_plot = test_dataset_plot.reset_index(drop=True)
test_dataset_plot["y_pred"] = y_pred_test
test_dataset_plot["residuo"] = test_dataset_plot[TARGET] - test_dataset_plot["y_pred"]

#Grafico 1:Brasil Real vs. Previsto por segmento (2025)
brasil = test_dataset_plot[test_dataset_plot["country"] == "Brazil"]

fig, ax = plt.subplots(figsize=(7, 4))
segments  = brasil["vehicle_segment"].unique()
colors    = {"commercial": "#378ADD", "mass_market": "#D85A30", "premium": "#2CA02C"}
x         = np.arange(len(segments))
width     = 0.35

real_vals  = [brasil[brasil["vehicle_segment"] == s][TARGET].values[0]  for s in segments]
pred_vals  = [brasil[brasil["vehicle_segment"] == s]["y_pred"].values[0] for s in segments]

bars_real = ax.bar(x - width/2, real_vals, width, label="Real",    color="#378ADD")
bars_pred = ax.bar(x + width/2, pred_vals, width, label="Previsto", color="#D85A30", alpha=0.8)

ax.set_xticks(x)
ax.set_xticklabels(["Comercial", "Popular", "Premium"])
ax.set_ylabel("EV Market Share (%)")
ax.set_title("Brasil 2025 — Real vs. Previsto por Segmento")
ax.legend()
ax.bar_label(bars_real, fmt="%.2f%%", padding=3, fontsize=9)
ax.bar_label(bars_pred, fmt="%.2f%%", padding=3, fontsize=9)
plt.tight_layout()
plt.show()

#Grafico 2: Top 10 países: erro absoluto do modelo em 2025
country_error = (test_dataset_plot
    .groupby("country")
    .apply(lambda x: np.mean(np.abs(x[TARGET] - x["y_pred"])))
    .sort_values(ascending=False)
    .head(50)
    .reset_index())
country_error.columns = ["country", "MAE"]

fig, ax = plt.subplots(figsize=(8, 4))
colors_bar = ["#D85A30" if c == "Brazil" else "#378ADD" for c in country_error["country"]]
ax.barh(country_error["country"][::-1], country_error["MAE"][::-1], color=colors_bar[::-1])
ax.set_xlabel("MAE (erro médio absoluto em pontos percentuais)")
ax.set_title("Top 10 países com maior erro de previsão — 2025\n(Brasil destacado em laranja)")
plt.tight_layout()
plt.show()

#Grafico 3: Dispersao Real vs. Previsto (todos os paises)
#A linha diagonal perfeita indica previsao sem erro
#Pontos acima = modelo subestimou; abaixo = superestimou

fig, ax = plt.subplots(figsize=(6, 6))
ax.scatter(
    test_dataset_plot[TARGET],
    test_dataset_plot["y_pred"],
    alpha=0.5, color="#378ADD", edgecolors="white", linewidth=0.5
)

#Linha de previsão perfeita (real = previsto)
lim = max(test_dataset_plot[TARGET].max(), test_dataset_plot["y_pred"].max()) * 1.05
ax.plot([0, lim], [0, lim], "--", color="#D85A30", linewidth=1.2, label="Previsão perfeita")

#Destaca o Brasil
brasil_scatter = test_dataset_plot[test_dataset_plot["country"] == "Brazil"]
ax.scatter(
    brasil_scatter[TARGET],
    brasil_scatter["y_pred"],
    color="#D85A30", s=80, zorder=5, label="Brasil"
)

ax.set_xlabel("Real (%)")
ax.set_ylabel("Previsto (%)")
ax.set_title("Real vs. Previsto — todos os países (2025)")
ax.legend()
plt.tight_layout()
plt.show()

"""## **10.1 Análise de erros e limitações**

**Erros**

O modelo tende a errar mais nos países com share mais alto, como Noruega e Suécia, justamente porque esses casos estão sub-representados no dataset (apenas 1.8% das observações passam de 50% de share, como identificado na AED). Com poucos exemplos de mercados em estágio avançado de adoção para aprender, o modelo tem dificuldade de prever com precisão esses casos extremos. No sentido oposto, o modelo também pode errar em países que passaram por uma aceleração brusca recente, como o Brasil entre 2021 e 2023, porque o histórico anterior de crescimento lento não prepara bem o modelo para capturar mudanças de regime na série.

**Overfitting/Underfitting**

O Random Forest apresentou sinais claros de overfitting: performou pior que os outros dois candidatos na validação (RMSE 6.37 vs. 4.37 do XGBoost), indicando que ajustou bem o período de treino mas não generalizou para 2023–2024. O XGBoost e a Regressão Linear não apresentaram sinais evidentes de nenhum dos dois problemas. Os resultados na validação e no teste são consistentes entre si, o que é um bom sinal de generalização. Não há sinais de underfitting em nenhum dos modelos, dado que todos superaram o baseline com folga e apresentaram R² acima de 0.94.

**Métrica**

O RMSE é uma boa métrica geral, mas tem uma limitação importante para este projeto: por penalizar mais os erros grandes, ele é fortemente influenciado pelos países líderes (Noruega, Suécia), que são os casos mais distantes do Brasil e menos relevantes para o objetivo central, que é prever quando o Brasil atingirá a paridade de 50%. Para esse objetivo específico, o MAE seria uma métrica mais honesta, por tratar todos os erros de forma igual e ser mais representativo do desempenho do modelo nos casos de share baixo, onde o Brasil se encontra. Idealmente, as duas métricas deveriam ser avaliadas em conjunto, com o MAE recebendo mais peso na decisão final sobre qual modelo usar para as projeções do Brasil.

**Viéses, limitação de dados ou risco de generalização**

Primeiro, o Brasil é o único país da América do Sul no dataset, ou seja, não há nenhum outro país com perfil econômico e regulatório similar para servir de referência próxima, o que significa que o modelo aprende padrões principalmente de países europeus e asiáticos e os aplica ao Brasil com risco de viés regional. Segundo, o dataset cobre até 2025 e foi construído com dados históricos que refletem um período específico de condições econômicas globais. Choques externos como crises de energia, mudanças abruptas de política pública ou variações bruscas no preço de commodities não estão representados e podem invalidar as previsões. Terceiro, a zero-inflação do target (57 observações exatamente em zero) identificada na AED não foi tratada com uma abordagem específica. Um modelo de regressão contínua trata zeros da mesma forma que valores baixos, o que pode introduzir viés nas previsões para mercados que ainda não decolaram.

**Cenários**

O modelo não deveria ser usado para prever cenários de ruptura, como uma mudança repentina e drástica na política de subsídios, uma crise econômica severa ou uma inovação tecnológica que altere radicalmente o custo dos veículos elétricos. Nesses casos, o modelo extrapolaria padrões históricos que deixariam de ser válidos. Também não deve ser usado para projeções de longo prazo além de 2 a 3 anos: a incerteza das previsões cresce rapidamente com o horizonte temporal, e o mercado de elétricos está em transformação rápida o suficiente para tornar o histórico recente pouco representativo do futuro distante. Por fim, não deve ser aplicado diretamente a países com perfil muito diferente dos que compõem o dataset (como países de baixa renda sem infraestrutura de energia elétrica consolidada) sem uma recalibração específica para esse contexto.

# **11. Comparação final dos modelos**

| Modelo | RMSE (métrica principal) | MAE / R² | Tempo de treino | Observações |
|---|---:|---:|---:|---|
| Baseline (lag1) | 22.67 | MAE: 15.50 / R²: -0.47 | 0.0s | R² negativo. Confirma que a inércia da série sozinha não é suficiente para capturar o crescimento acelerado do mercado |
| Regressão Linear | 4.45 | MAE: 2.73 / R²: 0.944 | 0.036s | Modelo mais simples e mais rápido. Menor MAE entre todos. Erra menos nos casos de share baixo, onde o Brasil está. Boa alternativa quando interpretabilidade é prioridade |
| Random Forest | 6.37 | MAE: 4.43 / R²: 0.884 | 2.84s | Pior candidato. Sinais de overfitting. Ajustou bem o período de treino mas não generalizou para a aceleração de 2023–2024 |
| XGBoost padrão | 4.37 | MAE: 3.11 / R²: 0.946 | 1.56s | Melhor RMSE entre os candidatos iniciais. Captura não-linearidades da curva S identificada na AED melhor que a Regressão Linear |
| XGBoost otimizado | **4.29** | MAE: 3.03 / R²: 0.948 | ~50s (busca) | Melhor modelo geral. Melhora consistente em todas as métricas após 50 iterações com TimeSeriesSplit. Modelo recomendado para as projeções do Brasil |

# **12. Boas práticas e rastreabilidade**

## **12.1 Configurações de reprodutibilidade**
- **Seed:** 42 aplicada em todos os modelos com componente aleatório (Random Forest, XGBoost, busca de hiperparâmetros)
- **Ambiente:** Python 3, Google Colab
- **Principais bibliotecas:** pandas, numpy, scikit-learn, xgboost, matplotlib

## **12.2 Principais decisões de pré-processamento**

| Decisão | Justificativa | Impacto esperado |
|---|---|---|
| Remover *is_ev_dominant* | Derivada deterministicamente do target (limiar de 50%) data leakage direto | Evitar desempenho artificial e inflado |
| Remover *co2_emissions_transport_mt* | Consequência da adoção de elétricos, não causa. Leakage conceitual por causalidade invertida | Evitar que o modelo aprenda uma relação espúria |
| Remover *avg_ev_range_km* | Correlação de 0.97 com *year*. Multicolinearidade que não acrescenta poder preditivo específico ao Brasil | Reduzir redundância sem perder informação |
| Remover *petrol_car_sales* e *diesel_car_sales* | Componentes diretos de *total_vehicle_sales*. Multicolinearidade com a variável agregada | Simplificar o conjunto de features sem perda de informação |
| Remover *ev_sales* e *ev_growth_rate_yoy* como features contemporâneas | Relação matemática direta com o target no mesmo período t. Leakage indireto | Evitar que o modelo use informação que não estaria disponível no momento da previsão |
| Reintroduzir *ev_sales* e *ev_growth_rate_yoy* como lags (t-1, t-2, t-3) | Transformar em informação legitimamente passada e disponível no momento da previsão | Preservar o sinal preditivo dessas variáveis sem leakage |
| Remover *total_vehicle_sales* | Correlação quase nula com o target (0.006). Sem poder preditivo relevante | Reduzir ruído no conjunto de features |
| Codificação ordinal de *vehicle_segment* | A AED mostrou hierarquia real de adoção: commercial < mass_market < premium | Preservar a relação ordinal entre segmentos, mais informativa que one-hot encoding |
| Aplicar log1p em variáveis com alta assimetria | *charging_stations*, *gdp_per_capita*, *ev_subsidy_usd* e lags de *ev_sales* têm cauda longa e range muito amplo | Reduzir influência de outliers extremos e estabilizar a variância |
| Aplicar StandardScaler apenas sobre o treino | Evitar que informação da validação e do teste contamine o ajuste do scaler. Data leakage de pré-processamento | Garantir avaliação justa e reproduzível do modelo |
| Divisão cronológica: treino ≤ 2022, validação 2023–2024, teste 2025 | Problema de série temporal. Embaralhar dados violaria a causalidade temporal | Simular o cenário real de previsão e evitar leakage temporal |
| Descartar primeiros 3 anos de cada série após engenharia de lags | Linhas sem histórico suficiente para gerar lag de 3 anos (valores NaN) | Garantir consistência do conjunto de features sem imputação artificial |

## **12.2 Modelos testados**

| Modelo | RMSE (validação) | MAE (validação) | R² (validação) | Tempo de treino | Situação |
|---|---:|---:|---:|---:|---|
| Baseline (lag1) | 22.67 | 15.50 | -0.47 | 0.0s | Descartado por R² negativo |
| Regressão Linear | 4.45 | 2.73 | 0.944 | 0.036s | Mantido como referência interpretável |
| Random Forest | 6.37 | 4.43 | 0.884 | 2.84s | Descartado por sinais de overfitting |
| XGBoost padrão | 4.37 | 3.11 | 0.946 | 1.56s | Candidato final |
| XGBoost otimizado | 4.29 | 3.03 | 0.948 | ~50s (busca) | **Modelo final selecionado** |

## **12.3 Hiperparâmetros do modelo final (XGBoost otimizado)**

| Hiperparâmetro | Valor encontrado | O que controla |
|---|---|---|
| n_estimators | 359 | Número de árvores sequenciais |
| learning_rate | ~0.154 | Velocidade de correção de erros a cada árvore |
| max_depth | 4 | Profundidade máxima de cada árvore |
| subsample | ~0.674 | Fração dos dados usada em cada árvore |
| colsample_bytree | ~0.673 | Fração das features usada em cada árvore |
| random_state | 42 | Semente para reprodutibilidade |

- **Estratégia de busca:** RandomizedSearchCV com 50 iterações
- **Validação cruzada:** TimeSeriesSplit com 5 folds (respeita ordem cronológica)
- **Métrica guia:** neg_root_mean_squared_error (RMSE)

## **12.4 Tentativas**

- **GridSearchCV com 20 iterações:** produziu um XGBoost otimizado com RMSE pior que o padrão (4.72 vs. 4.37). Insuficiente para cobrir o espaço de busca. Substituído por 50 iterações com RandomizedSearchCV.
- **Random Forest como modelo final:** descartado por overfitting. RMSE de 6.37 na validação, significativamente acima dos outros candidatos.
- **Pipeline com pré-processamento embutido:** descartado porque o pré-processamento foi aplicado diretamente em X_train, X_val e X_test nas etapas anteriores. Incluir novamente geraria conflito com o scaler já ajustado.
- **One-hot encoding de *vehicle_segment*:** substituído por codificação ordinal, que preserva a hierarquia real de adoção entre segmentos identificada na AED.
- **Modelos de série temporal puros (ARIMA, Prophet):** descartados por não suportarem covariáveis externas (preço de combustível, regulação, PIB), que são justamente as features mais relevantes segundo a análise de correlação.
- **Redes neurais (LSTM, GRU):** descartadas por exigirem volume de dados maior que o disponível (975 linhas) para generalizar bem sem overfitting.

## **12.5 Limitações conhecidas**

- O Brasil é o único representante da América do Sul no dataset. O modelo aprende principalmente de padrões europeus e asiáticos, com risco de viés regional nas projeções brasileiras.
- O modelo não captura choques externos (crises econômicas, mudanças abruptas de política pública, inovações tecnológicas disruptivas). Foi treinado em um período de crescimento relativamente estável.
- A zero-inflação do target (57 observações exatamente em zero) não foi tratada com uma abordagem específica. Um modelo de duas etapas poderia capturar melhor a transição entre "mercado que ainda não decolou" e "mercado em crescimento".
- Projeções além de 2 a 3 anos devem ser interpretadas com cautela. A incerteza cresce rapidamente com o horizonte temporal em mercados em transformação acelerada como o de veículos elétricos.

# **13. Conclusão**

**Objetivo do trabalho**

Este trabalho buscou entender em quais condições a adoção de veículos elétricos se torna economicamente viável no Brasil e quando as vendas de elétricos poderiam superar as de veículos a combustão. Para isso, foi construído um modelo preditivo capaz de estimar o share de mercado de elétricos a partir de variáveis estruturais (regulação ambiental, preço de combustível, PIB per capita, infraestrutura de recarga e histórico de adoção) usando um painel de 25 países entre 2010 e 2025.

**Melhor solução encontrada**

O modelo final selecionado foi o XGBoost com hiperparâmetros otimizados via busca aleatória com validação cronológica, atingindo RMSE de 4.29, MAE de 3.03 e R² de 0.948 no conjunto de validação. Isso significa que o modelo consegue prever o share de mercado de elétricos com um erro médio de cerca de 3 pontos percentuais, que foi resultado satisfatório para um target que varia de 0% a 95% e que inclui mercados em estágios muito diferentes de maturidade. A Regressão Linear apresentou desempenho competitivo (RMSE 4.45, MAE 2.73), com menor erro médio nos casos de share baixo, que são justamente os mais representativos do contexto brasileiro atual.

**Comparação com baseline**

O modelo final superou o baseline com ampla margem: o RMSE caiu de 22.67 (baseline ingênuo por lag1) para 4.29, uma redução de 81%. O R² negativo do baseline (-0.47) confirmou que simplesmente repetir o valor do ano anterior é insuficiente para capturar a dinâmica de crescimento acelerado do mercado de elétricos, validando a necessidade de um modelo que incorpore as variáveis estruturais identificadas na análise exploratória.

**Hipóteses**

1. **Hipótese 1: A adoção de veículos elétricos está mais associada a fatores regulatórios e econômicos do que a subsídios diretos.**\
**CONFIRMADA**\
A análise de correlação mostrou *emission_regulation_score* = 0.59 e
*fuel_price* = 0.55 com o target, contra *ev_subsidy_usd* = -0.06, diferença
muito superior ao critério de duas vezes estabelecido. Subsídios diretos
isoladamente não se mostraram determinantes para a adoção de veículos elétricos. Regulação ambiental forte e combustível caro são os fatores estruturais mais associados à transição, o que sugere que políticas públicas focadas apenas em incentivos financeiros têm impacto limitado sem o suporte dessas condições de base.

2. **Hipótese 2: Variáveis estruturais de mercado têm poder preditivo suficiente para estimar o share de veículos elétricos com erro médio inferior a 5 pontos percentuais.**\
**CONFIRMADA**\
O XGBoost otimizado com features estruturais atingiu RMSE de 4.29 e MAE de
3.03 no conjunto de validação, contra RMSE de 22.67 do baseline ingênuo, redução de 81%, muito acima do critério mínimo de 50%. O MAE de 3.03 pontos
percentuais ficou abaixo do limite de 5 estabelecido como critério de sucesso.
Todos os três modelos candidatos superaram o baseline com folga, confirmando
que as variáveis estruturais carregam informação preditiva real sobre a
trajetória de adoção de elétricos.

3. **Hipótese 3: O Brasil está em estágio inicial da curva de difusão de veículos elétricos, com trajetória de crescimento acelerado a partir de 2021.**\
**CONFIRMADA**\
A análise temporal da série brasileira mostrou crescimento praticamente nulo
entre 2010 e 2020, inflexão visível em 2021–2022 (crescimento de 139% e 290%
a.a. respectivamente) e aceleração progressiva até 3.75% de share em 2025,
formato característico da fase inicial de uma curva S de difusão tecnológica.
O Brasil ocupou a 22ª posição entre 25 países em 2025, com share muito abaixo
da mediana global de 14.48%, confirmando que a transição está em estágio
emergente. A inflexão já ocorreu, mas a distância até a paridade de 50% ainda
é considerável e depende de avanços simultâneos em múltiplas condições estruturais.

**Principais aprendizados**

A análise exploratória revelou que a adoção de veículos elétricos não depende de um único fator, mas de um conjunto integrado de condições, como regulação ambiental forte, combustível caro, renda elevada e maturidade tecnológica. Subsídios isolados mostraram correlação fraca com o share de mercado, o que sugere que políticas públicas focadas apenas em incentivos financeiros têm impacto limitado sem o suporte das demais condições estruturais. O Brasil, com share de 3.75% em 2025 e ocupando a 22ª posição entre 25 países, está na transição entre os estágios emergente e de crescimento da curva de difusão, o que indica que a inflexão já ocorreu, mas a distância até a paridade de 50% ainda é considerável e depende de avanços simultâneos em múltiplas frentes.

**Limitações**

O modelo foi construído sobre dados históricos que refletem condições específicas de um período de crescimento relativamente estável. Não captura choques externos, mudanças abruptas de política ou inovações tecnológicas disruptivas. O Brasil é o único representante da América do Sul no painel, o que significa que o modelo aprende principalmente de padrões europeus e asiáticos com risco de viés regional nas projeções brasileiras. Adicionalmente, a zero-inflação do target e a concentração de casos em share baixo limitam a precisão do modelo justamente na faixa de transição mais relevante para o Brasil.

**Próximos passos**

Três frentes se destacam como continuação natural deste trabalho. A primeira é ajustar um modelo de difusão não-linear (Bass) aos dados históricos do Brasil para estimar formalmente os parâmetros de inovação e imitação da curva S e projetar o ano de paridade. A segunda é implementar a análise de sensibilidade para variar preço de combustível e subsídios em ±20% e medir o deslocamento do ano de paridade previsto, transformando o modelo em uma ferramenta de simulação de cenários para formuladores de políticas públicas. A terceira é explorar uma abordagem de modelagem em duas etapas: primeiro classificar se o mercado já decolou, depois regredir a magnitude do share, para tratar adequadamente a zero-inflação do target e melhorar a precisão das previsões justamente na faixa onde o Brasil se encontra hoje.
"""